/*******************************************************************************
* File Name: project.h
* 
* PSoC Creator  4.4
*
* Description:
* It contains references to all generated header files and should not be modified.
* This file is automatically generated by PSoC Creator.
*
********************************************************************************
* Copyright (c) 2007-2020 Cypress Semiconductor.  All rights reserved.
* You may use this file only in accordance with the license, terms, conditions, 
* disclaimers, and limitations in the end user license agreement accompanying 
* the software package with which this file was provided.
********************************************************************************/

#include "cyfitter_cfg.h"
#include "cydevice_trm.h"
#include "cyfitter.h"
#include "cydisabledsheets.h"
#include "RX.h"
#include "RX_aliases.h"
#include "TX.h"
#include "TX_aliases.h"
#include "CAN.h"
#include "RightBlinker_BTN.h"
#include "RightBlinker_BTN_aliases.h"
#include "LeftBlinker_BTN.h"
#include "LeftBlinker_BTN_aliases.h"
#include "Hazard_BTN.h"
#include "Hazard_BTN_aliases.h"
#include "HeadLights_BTN.h"
#include "HeadLights_BTN_aliases.h"
#include "Brake_SW.h"
#include "Brake_SW_aliases.h"
#include "FrontLeftBlinker.h"
#include "FrontLeftBlinker_aliases.h"
#include "FrontRightBlinker.h"
#include "FrontRightBlinker_aliases.h"
#include "HeadLights.h"
#include "HeadLights_aliases.h"
#include "RearLeftBrake.h"
#include "RearLeftBrake_aliases.h"
#include "RearRightBrake.h"
#include "RearRightBrake_aliases.h"
#include "RearCenterBrake.h"
#include "RearCenterBrake_aliases.h"
#include "RightBlinkers.h"
#include "LeftBlinkers.h"
#include "Clock.h"
#include "Brakes.h"
#include "CAN_isr.h"
#include "CAN_HFCLK.h"
#include "core_cm0_psoc4.h"
#include "CyFlash.h"
#include "CyLib.h"
#include "cyPm.h"
#include "cytypes.h"
#include "cypins.h"
#include "CyDMA.h"
#include "CyLFClk.h"
#include "cy_em_eeprom.h"

/*[]*/

